// Generated by scripts/measure-aura-tracks.mjs. Do not edit by hand:
// put manual corrections in AURA_TRACK_OVERRIDES inside AuraTracks.ts.
export const AURA_TRACKS_GENERATED = [
  {
    id: 'neon-arena',
    title: 'Neon Arena',
    url: '/assets/audio/neon-arena-battle-v1.mp3',
    bpm: 153.75,
    beatOffsetMs: 57,
    durationMs: 295014,
    stageId: 'insert-player-arena',
  },
  {
    id: 'neon-arena-155',
    title: 'Neon Arena 155',
    url: '/assets/audio/aura/neon-arena-155.mp3',
    bpm: 155,
    beatOffsetMs: 366,
    durationMs: 120000,
    stageId: 'insert-player-arena',
  },
] as const;
